;不要随意改变关键字，否则会导致出错
;acl4SSR规则

;功能支持
;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持

;设置规则标志位
ruleset=🎯 全球直连,https://raw.githubusercontent.com/cmliu/ACL4SSR/refs/heads/main/Clash/CFnat.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/adobe.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/IDM.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list

;广告拦截规则修正，使用 REJECT 避免报错
DOMAIN-KEYWORD,admarvel,REJECT
DOMAIN-KEYWORD,ads,REJECT
DOMAIN-KEYWORD,tracking,REJECT
DOMAIN-KEYWORD,google-analytics,REJECT

;设置分组标志位
custom_proxy_group=📶 官方优选`load-balance`(官方|防|电信|联通|移动|CT|CU|CM|CF|t.me|WARP|Warp|warp)`http://www.gstatic.com/generate_204`300,,50

;确保官方优选的节点优先选择
custom_proxy_group=🎯 全球直连`select`[]📶 官方优选`[]DIRECT

;启用自动测速功能
custom_proxy_group=🚀 自动测速`url-test`[]📶 官方优选`http://www.gstatic.com/generate_204`300,,50

;启用分流规则：微软、苹果分流
custom_proxy_group=Ⓜ️ 微软服务`select`[]📶 官方优选`[]DIRECT
custom_proxy_group=🍎 苹果服务`select`[]📶 官方优选`[]DIRECT

;增强国内IP段和国外GFW增强
custom_proxy_group=🎯 全球直连`select`[]📶 官方优选`[]DIRECT
custom_proxy_group=🌏 国内媒体`select`[]📶 官方优选`[]DIRECT
custom_proxy_group=🌍 国外媒体`select`[]📶 官方优选`[]DIRECT

;启用规则生成器
enable_rule_generator=true
overwrite_original_rules=true

;基础规则文件（可选）
;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

;luck
